[build-system]
requires = ["setuptools>=41.0.1", "wheel", "scikit-build>=0.9.0", "numpy"]

[tool.cibuildwheel]
build = "*"
skip = "pp*"
build-verbosity = 1

manylinux-x86_64-image = "quay.io/erotemic/manylinux2014_x86_64_for:lz4"
manylinux-i686-image = "quay.io/erotemic/manylinux2014_i686_for:lz4"
musllinux-x86_64-image = "quay.io/erotemic/musllinux2014_x86_64_for:lz4"
musllinux-i686-image = "quay.io/erotemic/musllinux2014_i686_for:lz4"

manylinux-aarch64-image = "quay.io/erotemic/manylinux2014_aarch64_for:lz4"
musllinux-aarch64-image = "quay.io/erotemic/musllinux2014_aarch64_for:lz4"

#manylinux-ppc64le-image
#manylinux-s390x-image


#before-all = ""
#before-build = ""
#CIBW_BEFORE_BUILD_MACOS
#CIBW_BEFORE_BUILD_WINDOWS
#CIBW_BEFORE_BUILD_WINDOWS
